on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04
    name: Update NuGet package
    steps:

      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v1
        with:
          source-url: https://nuget.pkg.github.com/Scholtz/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_TOKEN}}        
          
      - name: Debug
        run: ls && pwd
        
      - name: Build solution
        run: dotnet build --configuration Release RestDWH.sln
        
      - name: Debug
        run: cd RestDWH && ls && pwd
        
      - name: Build solution and generate NuGet package
        run: |  
          cd RestDWH
          ls && pwd
          dotnet pack -c Release -o out
          ls && pwd

      - name: Push generated package to GitHub registry
        run: dotnet nuget push ./RestDWH/out/*.nupkg --skip-duplicate --no-symbols true  --api-key ${{secrets.NUGET_TOKEN}}
